### ISSUE TITLE
mongod.log permissions

### ISSUE THREAD

**Issue by gwbischof** [rhysmeister/AutomatingMongoDBWithAnsible#1]
After making the vagrant vms for a sharded cluster.
I did a vagrant down.
Then vagrant up again.
Then I checked the mongod status and it wasn't running.

`sudo service mongod start`, failed.

I tried `vagrant reload --provision`, which failed with error.
`
fatal: [mongodb1]: FAILED! => {"changed": false, "msg": "Unable to start service mongod: Job for mongod.service failed because the control process exited with error code.\nSee \"systemctl status mongod.service\" and \"journalctl -xe\" for details.\n"}
`

`mongod --config /etc/mongod.conf`,  failed with error:
```
Failed global initialization: FileNotOpen: Failed to open "/var/log/mongodb/mongod.log"
```

This file existed:
`
-rw-r-----. 1 mongod mongod 2861679 Oct  5 15:38 /var/log/mongodb/mongod.log
`

I adjusted the permission and then
`mongod --config /etc/mongod.conf` works.

Should we adjust the permissions of this file in the roles?

Thanks!

**Comment by gwbischof** [comment]
Oh, nevermind. I see that this process needs to be started as the mongod user

**Comment by gwbischof** [comment]
Hmm, actually, shouldn't `vagrant reload --provision` work and start the process as the mongod user?

**Comment by rhysmeister** [comment]
Hello,

These seems to be a problem on the config server mongod instances (i.e. mongos1-3 not on mongodb1-6).

`2020-10-14T13:13:26.191+0000 I  CONTROL  [main] ERROR: Cannot write pid file to /var/run/mongodb/mongod.pid: No such file or directory`

I'll take a look at this as soon as I can.

Rhys

**Comment by rhysmeister** [comment]
Hello @gwbischof,

This issue totally slipped off my radar but this was fixed ages ago. 

Cheers,

Rhys
